### ISSUE TITLE
Insertion error when using `meteor-autoform`

### ISSUE THREAD

**Issue by settinghead** [gliesesoftware/mylar#5] opened 2015-01-08 21:12 UTC
When trying to insert a record inside a form generated by `autoForm` helper from [meteor-autoform](https://github.com/aldeed/meteor-autoform) package, I received the following error:
```
Error: Can't set timers inside simulations {stack: (...), message: "Can't set timers inside simulations"} Error: Can't set timers inside simulations
    at withoutInvocation (http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:433:13)
    at bindAndCatch (http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:441:33)
    at Object._.extend.defer (http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:496:26)
    at LocalCollection.insert (http://localhost:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:634:12)
    at m.(anonymous function) (http://localhost:3000/packages/mongo.js?052f30e968644b2b39a96605ffee73a7684ff37b:920:45)
    at http://localhost:3000/packages/mylar_meteor-changes.js?aedc8898a58c86f279ed03c0213b180f9b269767:207:857
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:949:17)
    at connection.constructor.apply (http://localhost:3000/packages/mylar_meteor-changes.js?aedc8898a58c86f279ed03c0213b180f9b269767:207:696)
    at Mongo.Collection.(anonymous function) (http://localhost:3000/packages/mylar_meteor-changes.js?aedc8898a58c86f279ed03c0213b180f9b269767:162:34)
    at null.<anonymous> (http://localhost:3000/packages/matb33_collection-hooks.js?add77d962917951b78b0e03b248208918d7fbb41:367:19)
```

I was trying to identify the cause but gave up after an hour. Any idea what the cause might be? Thanks!

**Comment by ramijarrar** [comment] 2015-01-09 14:35
I am fairly certain that autoform is the cause of this issue as the error message states that the source is in one of your method simulations and this is not something that the mylar packages concern themselves with. 

A quick search on the meteor-autoform repo reveals [a similar issue](https://github.com/aldeed/meteor-autoform/issues/366) that has recently been solved so I would say that's probably the best place to start.

I'm going to close this issue for now but if you can isolate it to a mylar package then I will definitely take a closer look.

**Closed by ramijarrar** 2015-01-09 14:35 UTC

**Comment by settinghead** [comment] 2015-01-09 14:42
@ramijarrar Thanks! I'll take a closer look later today.
